spring:
  profiles:
    include:
      - aws
#    datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/issuetracker
#    username: root
#    password:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      schema-locations:
        - classpath:db/schema.sql
      data-locations:
        - classpath:db/data.sql
      mode: always
      encoding: UTF-8

logging:
  level:
    root: info
    team29.hoorry.issuetracker: debug
    org.hibernate.SQL: debug
