spring:
#  profiles:
#    active: ${profile}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/issuetracker
    username: root
    password:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
