name: deploy be

on:
  push:
    branches: [ "be-deploy" ]

permissions:
  contents: read

jobs:
  job:
    name: build and deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BE

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      
    - name: setup jdk 11
      uses: actions/setup-java@v3
      with:
        java-version: "11"
        distribution: "temurin"
    
    - name: grant execute permission for gradlew
      run: chmod +x gradlew

    - name: build gradle
      run: ./gradlew clean build

    - name: zip jar
      run: zip -qq -r issue-tracker.zip build/libs/*.jar appspec.yml deploy.sh

    - name: configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1 
      with: 
        aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }} 
        aws-region: ap-northeast-2

    - name: upload to S3
      run: aws s3 cp issue-tracker.zip s3://${{ secrets.AWS_S3_BUCKET_NAME }}/be/issue-tracker.zip

    - name: configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1 
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }} 
        aws-region: ap-northeast-2

    - name: CodeDeploy
      run: aws deploy create-deployment --application-name issue-tracker-be --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name issue-tracker-codedeploy-group --s3-location bucket=team29-issue-tracker,bundleType=zip,key=be/issue-tracker.zip
